/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sileader_cyborg_basys_Basys */

#ifndef _Included_net_sileader_cyborg_basys_Basys
#define _Included_net_sileader_cyborg_basys_Basys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sileader_cyborg_basys_Basys
 * Method:    setUid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sileader_cyborg_basys_Basys_setUid
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sileader_cyborg_basys_Basys
 * Method:    getUid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sileader_cyborg_basys_Basys_getUid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
