#
# libbasys
# (C) 2017 SiLeader.
#

LIB_NAME = libbasys.so

VERSION = 1.0.0
TARGET = $(LIB_NAME).$(VERSION)

CC = clang
CXX = clang++
LINK = clang++

build:
	$(CXX) -fPIC -shared -o $(TARGET) basys.cpp
